- name: Automated environment installation
  hosts: localhost
  gather_facts: true
  vars:
    home_folder: "{{ lookup('env', 'HOME') }}"
    src_git_key: "./tasks/global/keys/id_rsa"
    src_server_key: "./tasks/global/keys/id_rsa_servers"
    src_server_pub: "./tasks/global/keys/id_rsa_servers.pub"
    dst_git_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    dst_server_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_servers"
    dst_server_pub: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_servers.pub"
    personal_project_folder: "{{ lookup('env', 'HOME') }}/Projects/Personal"
  tasks:
    - name: Starting installer
      ansible.builtin.include_tasks: "./tasks/{{ ansible_distribution }}/init.yml"
# --------------------------------------------------------------------------
# ansible_distribution
#  - Archlinux
#  - Fedora
#  - MacOSX
