- name: Automated environment installation
  hosts: localhost
  gather_facts: true
  vars:
    home_folder: "{{ lookup('env', 'HOME') }}"
    src_git_key: "./tasks/Global/keys/id_ed_personal"
    src_server_key: "./tasks/Global/keys/id_ed_servers"
    src_server_pub: "./tasks/Global/keys/id_ed_servers.pub"
    src_gpg_key: "./tasks/Global/keys/private-gpg-key.asc"
    dst_git_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed_personal"
    dst_server_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed_servers"
    dst_server_pub: "{{ lookup('env', 'HOME') }}/.ssh/id_ed_servers.pub"
    dst_gpg_key: "{{ home_folder }}/.ssh/private-gpg-key.asc"
    personal_project_folder: "{{ lookup('env', 'HOME') }}/Projects/Personal"
  tasks:
    # Archlinux
    - name: Starting Archlinux installer
      ansible.builtin.import_tasks: "./tasks/Archlinux/init.yml"
      when: ansible_distribution == "Archlinux"
    # Fedora
    - name: Starting Fedora installer
      ansible.builtin.import_tasks: "./tasks/Fedora/init.yml"
      when: ansible_distribution == "Fedora"
    # MacOSX
    - name: Starting MacOSX installer
      ansible.builtin.import_tasks: "./tasks/MacOSX/init.yml"
      when: ansible_distribution == "MacOSX"
# --------------------------------------------------------------------------
# ansible_distribution
#  - Archlinux
#  - Fedora
#  - MacOSX
