- name: Automated environment installation
  hosts: localhost
  gather_facts: true
  vars:
    home_folder: "{{ lookup('env', 'HOME') }}"
    vault_keys_folder: "./tasks/Global/keys"
    src_git_key: "{{ vault_keys_folder }}/id-ed-personal"
    src_gpg_key: "{{ vault_keys_folder }}/personal-gpg-private.asc"
    dst_git_key: "{{ home_folder }}/.ssh/id-ed-personal"
    dst_gpg_key: "{{ home_folder }}/.ssh/personal-gpg-private.asc"
    personal_project_folder: "{{ home_folder }}/Projects/Personal"
  tasks:
    - name: Debug ansible distribution
      ansible.builtin.debug:
        var: ansible_distribution
      tags:
        - debug
    # Archlinux
    - name: Starting Archlinux installer
      ansible.builtin.import_tasks: "./tasks/Archlinux/init.yml"
      when: ansible_distribution == "Archlinux"
    # Fedora
    - name: Starting Fedora installer
      ansible.builtin.import_tasks: "./tasks/Fedora/init.yml"
      when: ansible_distribution == "Fedora"
    # Ubuntu
    - name: Starting Ubuntu installer
      ansible.builtin.import_tasks: "./tasks/Ubuntu/init.yml"
      when: ansible_distribution == "Ubuntu"
    # MacOSX
    - name: Starting MacOSX installer
      ansible.builtin.import_tasks: "./tasks/MacOSX/init.yml"
      when: ansible_distribution == "MacOSX"
      
# --------------------------------------------------------------------------
# ansible_distribution
#  - Archlinux
#  - Fedora
#  - MacOSX
