# Perform Global task regardles of the OS
- hosts: localhost
  vars:
    src_git_key: "./global/keys/id_rsa"
    src_server_key: "./global/keys/id_rsa_servers"
    src_server_pub: "./global/keys/id_rsa_servers.pub"
    dst_git_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    dst_server_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_servers"
    dst_server_pub: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_servers.pub"
  tasks:
    - import_tasks: ./global/ssh.yml

