# Essential keychain
- name: Install build tools
  become: true
  dnf:
    name:
      - "@C Development Tools and Libraries"
      - "@Development Tools"
      - cmake
      - tree-sitter-cli
      - libtree-sitter
    state: latest
  tags:
    - development

# Install Go
- name: Install Programming Languages
  become: true
  dnf:
    name:
      - golang
      - delve
      - php
      - composer
      - nodejs
      - npm
    state: latest
  tags:
    - development

- name: Installing global tools
  ansible.builtin.import_tasks: ../Global/development.yml

