# Essential keychain
- name: Install build tools
  become: true
  dnf:
    name:
      - "@C Development Tools and Libraries"
      - "@Development Tools"
      - cmake
      - tree-sitter-cli
      - libtree-sitter
    state: latest
  tags:
    - development
  when: ansible_distribution == "Fedora"

# Install Go
- name: Install GoLang
  become: true
  dnf:
    name:
      - golang
    state: latest
  tags:
    - development
  when: ansible_distribution == "Fedora"

