# Increase the number of parallel downloads
- name: Update dnf.conf
  become: true
  shell: echo 'max_parallel_downloads=10' >> /etc/dnf/dnf.conf
  tags:
    - init
  when: ansible_distribution == "Fedora"

# Upgrade all packages
- name: Upgrade all packages
  become: true
  dnf:
    name: "*"
    state: latest
  tags:
    - init
  when: ansible_distribution == "Fedora"

# Enable rpmfusion free
- name: Enable RPM Fusion Free
  become: true
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  tags:
    - init
  when: ansible_distribution == "Fedora"
