# Install base console commands
- name: Install zsh and dependencies
  become: true
  community.general.pacman:
    name:
      - zsh
      - bat
      - exa
      - tree
      - tmux
      - neovim
      - xclip
      - curl
      - wget
      - fzf
      - ripgrep
      - xclip
      - curl
      - wget
    state: present
  tags:
    - terminal




