# Install base console commands
- name: Install zsh and dependencies
  become: true
  ansible.builtin.dnf:
    name:
      - zsh
      - bat
      - exa
      - tree
      - tmux
      - neovim
      - xclip
      - curl
      - wget
      - fzf
      - ripgrep
      - xclip
      - curl
      - wget
      - zip
    state: present
  tags:
    - terminal

- name: Importing global terminal task
  ansible.builtin.import_tasks: ../Global/terminal.yml
