- name: Install basics
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - base
      - base-devel
      - archlinux-keyring
      - udiskie
      - udisks2
      - usbutils
      - pacman-contrib
      - pipewire
      - pipewire-pulse
      - libpipewire
      - lib32-libpipewire
      - bluez
      - bluez-utils
      - openssh
      - stow
      - ntfs-3g
      - zip
      - unzip
      - exfat-utils
    state: present
  tags:
    - basics

- name: Checkout yay project
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "{{ home_folder }}/yay"
  tags:
    - basics

- name: Make the package
  ansible.builtin.command: makepkg -si --noconfirm
  args:
    chdir: "{{ home_folder }}/yay"
  tags:
    - basics

- name: Remove yay folder
  ansible.builtin.file:
    state: absent
    path: "{{ home_folder }}/yay"
  tags:
    - basics

- name: Install firmware drivers
  ansible.builtin.shell: yay -S aic94xx-firmware wd719x-firmware --needed --noconfirm
  tags:
    - basics

