- name: Install dependencies
  become: true
  community.general.pacman:
    name:
      - base-devel
      - hunspell    # Gospel dependency
      - go
      - delve       # Golang Debugger
      - php
      - composer
      - nodejs
      - npm
      - docker
      - docker-compose
      - mariadb-clients
    state: present
    extra_args: --needed

- name: Installing global tools
  ansible.builtin.import_tasks: ../Global/development.yml
