- name: Install dependencies
  become: true
  community.general.pacman:
    name:
      - base-devel
      - fzf
      - ripgrep
      - hunspell    # Gospel dependency
      - github-cli  # For neovim octo plugin
      - go
      - delve       # Golang Debugger
    state: present
    extra_args: --needed

- name: Installing global tools
  ansible.builtin.import_tasks: ../Global/development.yml
