- name: Install amd drivers
  become: true
  community.general.pacman:
    name:
      - mesa
      - lib32-mesa
      - vulkan-radeon
      - lib32-vulkan-radeon
      - xf86-video-amdgpu
      - libva-mesa-driver
      - lib32-libva-mesa-driver
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - mesa-vdpau
      - lib32-mesa-vdpau
      - vulkan-mesa-layers
      - lib32-vulkan-mesa-layers
      - mesa-demos
      - xorg-xdriinfo
      - vulkan-radeon 
      - lib32-vulkan-radeon 
    state: present
    extra_args: --needed
  tags:
    - drivers

- name: Install smartcard reader drivers
  become: true
  community.general.pacman:
    name:
      - ccid
      - opensc
      - pcsc-tools
    state: present
    extra_args: --needed
  tags:
    - drivers

- name: Start pcsc service
  become: true
  shell: systemctl enable --now pcscd.service
  tags:
    - drivers
