- name: Gnome Archlinux (btw)
  become: true
  community.general.pacman:
    name:
      - gnome
      - gnome-themes-extra
      - gnome-tweaks
      - pipewire-jack
      - lib32-pipewire-jack
      - xdg-utils
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-ugly
      - gst-plugin-pipewire
      - eog
      - firefox
      - kitty
      - kvantum-qt5
      - libreoffice-fresh
      - fragments
      - d-spy
      - dconf-editor
      - file-roller
      - gnome-boxes
      - gnome-builder
      - gnome-connections
      - gnome-multi-writter
      - gnome-sound-recorder
      - seahorse
      - simple-scan
      - sysprof
    state: present
  tags:
    - gnome


# Install software from aur
- name: Install desktop apps from aur
  become: false
  ansible.builtin.shell: |
    yay -S \
    1password spotify google-chrome gnome-browser-connector \
    --needed --noconfirm
  tags:
    - gnome

# Enable GDM
- name: Enable GDM
  become: true
  ansible.builtin.systemd:
    name: gdm
    enabled: true
  tags:
    - gnome

# Include gnome global configuration
- name: Include global Gnome config
  ansible.builtin.import_tasks: ../Global/gnome.yml
  tags:
    - gnome
