- name: Debugging something
  debug: msg="This is the way"

- name: Gnome Shortcuts
  become_user: pablo
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-down"
    value: "'<Alt>9'"
  tags:
    - gnome
    - untested
