- name: Running Archlinux installation script
  block:
    # Import ssh keys
    - name: Running ssh tasks
      ansible.builtin.import_tasks: ./ssh.yml

    # Install basics
    - name: Install basics
      ansible.builtin.import_tasks: ./basics.yml

    - name: Install drivers
      ansible.builtin.import_tasks: ./drivers.yml

    # Install terminal stuff
    - name: Install terminal stuff
      ansible.builtin.import_tasks: ./terminal.yml

    # Install dotfiles
    - name: Installing dotfiles
      ansible.builtin.import_tasks: ./dotfiles.yml

    # Install development stuff
    - name: Install development stuff
      ansible.builtin.import_tasks: ./development.yml

    # Install destop stuff (gnome)
    - name: Install desktop environment stuff
      ansible.builtin.import_tasks: ./plasma.yml

    # Install gaming stuff (just steam for now)
    - name: Install gaming stuff
      ansible.builtin.import_tasks: ./gaming.yml
