- name: Plasma Archlinux (btw)
  become: true
  community.general.pacman:
    name:
      - plasma
      - plasma-wayland-session
      - kde-applications
      - kalarm
      - libreoffice-fresh
      - sddm
      - plasma-workspace
      - wl-clipboard
    state: present
    extra_args: --needed
  tags:
    - plasma


    # Install software from aur
- name: Install desktop apps from aur
  become: false
  ansible.builtin.shell: |
    yay -S \
    1password spotify google-chrome \
    --needed --noconfirm
  tags:
    - plasma

- name: Enable sddm
  become: true
  ansible.builtin.systemd:
    name: sddm
    enable: true
  tags:
    - plasma

