- name: Update mirror cache and update the OS
  become: true
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
  tags:
    - basics

- name: Install Basics
  become: true
  ansible.builtin.apt:
    name:
      - git
      - fzf
    state: present
  tags:
    - basics
