- name: Install dependencies
  become: true
  ansible.builtin.apt:   
    pkg:
      - build-essential
      - cmake
    state: present
  tags:
    - development

- name: Installing global tools
  ansible.builtin.import_tasks: ../Global/development.yml
 