- name: Install terminal stuff
  become: true
  ansible.builtin.apt:
    pkg:
      - zsh
      - bat
      - exa
      - tmux
      - fd-find
    state: present
  tags:
    - terminal

- name: Importing global terminal task
  ansible.builtin.import_tasks: ../Global/terminal.yml
