# Create project directory
- name: Creating projects directory
  file:
    path: "{{ personal_project_folder }}"
    state: directory
  tags:
    - dotfiles

- name: Debug ansible distribution
  ansible.builtin.debug:
    var: dst_git_key
  tags:
    - dotfiles

# Checkout dotfiles
- name: Checking out dotfiles
  git:
    repo: "https://github.com/polivera/dotfiles"
    dest: "{{ personal_project_folder }}/dotfiles"
  tags:
    - dotfiles

- name: Install dotfiles
  ansible.builtin.shell: "{{ personal_project_folder }}/dotfiles/install.sh"
  register: foobar
  tags:
    - dotfiles
  