# Create project directory
- name: Creating projects directory
  file:
    path: "{{ personal_project_folder }}"
    state: directory
  tags:
    - dotfiles

# Checkout dotfiles
- name: Checking out dotfiles
  ansible.builtin.git:
    repo: "git@gh.personal:polivera/dotfiles"
    dest: "{{ personal_project_folder }}/dotfiles"
  tags:
    - dotfiles

- name: Install dotfiles
  ansible.builtin.shell: "{{ personal_project_folder }}/dotfiles/install.sh"
  register: foobar
  tags:
    - dotfiles
