# Change the default shel
- name: Change default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  tags:
    - terminal

# Install starship
- name: Install starship shell
  ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  tags:
    - terminal

# Installing tmux tpm
- name: Installing tmux tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux/plugins/tpm"
    version: master
  tags:
    - terminal
